[package]
name = "dicenet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ocelot = {git = "https://github.com/GaloisInc/swanky.git", branch = "dev"}
fancy-garbling = {git = "https://github.com/GaloisInc/swanky.git", branch = "dev"}
scuttlebutt = {git = "https://github.com/GaloisInc/swanky.git", branch = "dev"}
clap = { version = "4.4.18", features = ["derive"] }
colored = "1.8.0"
image = "0.24.8"
itertools = "0.8.0"
ndarray = "0.13.0"
pbr = "1.0.2"
serde = "1.0.101"
serde_json = "1.0.40"
